### ISSUE TITLE
Conditionally render a component

### ISSUE THREAD

**Issue by deepakkumardk** [sandarshnaroju/react-native-nano#9]
First Thanks & great job on this library, it really helps to make MVP quickly.

How can we render a component conditionally based on state (nano value key), a simple use case would be I want to show the image/video only after the user has selected it, so in the image/video component I need to set `value: getUi('selectedFile').value` but since `value` is not a function we can't do that also it hasn't the short circuit thing handled.

The hotfix for now would be to make our custom component for Image and Video which will handle the null value, but if that can done with nano that would be great.

**Comment by sandeshnaroju** [comment]
Hey, thanks for trying the library, Can you be more clear on what you are trying to do? I am assuming that you are trying to select a file  and if the file is of type image, then render image component otherwise video component? 

```javascript
const selectFileButton = {
    name: "select_file",
    component: NANO.ICON_BUTTON,
    value: 'pencil',
    props: {
        size: 24,
        color: 'black',
        style: {
        }
    },
    hide: false,
    onPress: async ({ setUi, getUi, moduleParams }) => {
        const {  imagePicker } = moduleParams

        const videoObj = getUi("video")
        const imageObj = getUi("image")

        let data = null
        try {
            const image = await imagePicker.openPicker({
                width: 100,
                height: 100,
                cropping: true
            })
             if(image.mime=="image/png"){
               videoObj.hide = true
               imageObj.value = image.path
               imageObj.hide = false
             }else{
               videoObj.hide = false
               imageObj.value = image.path
               imageObj.hide = true             
             }
            setUi("image", imageObj)
            setUi("video", videoObj)       
 
        } catch (error) {
            console.log(error)
        }

    }
};
```

The above code just gives you an idea, you may have to use filePicker which can pick any kind of file not just image, the above example is just to give you an idea. helpful ?

**Comment by deepakkumardk** [comment]
Thanks for the quick reply, that's exactly what I needed, `hide` prop for components, Thanks Again.

**Comment by deepakkumardk** [comment]
Just curious about this great library, what are the future plans and taking PR or opening GitHub discussions?

**Comment by sandeshnaroju** [comment]
We have created documentation at docs.nanoapp.dev. We would love to accept PR's, the idea is to create an easy to use library in JSON way and load it from server, so that developer does not have to update their apks/aab to stores whenever they need any change. We are also working on code.nanoapp.dev a tool where anyone can code and load UI from cloud it is not fully completed anyway, we are hoping to launch it soon with all support.  I want to hope you came across this repo?

**Comment by deepakkumardk** [comment]
I did found this repo last year while looking for low code with json, at that time it was young, and I also didn't get time to look it again, and while going through my GitHub repo I just saw this repo, and tried in my playground app. very promising.

**Comment by sandeshnaroju** [comment]
Thanks for the feedback.

**Comment by sandeshnaroju** [comment]
Feel free to open issues and we are working full time on this to develop quicker. Thanks
